name: Checks

on:
  push:
    branches:
      - main
    tags-ignore:
      - "**"
  pull_request:
    branches:
      - main

jobs:

  check-syntax:
    name: PHP ${{ matrix.php-version }} Syntax
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-version:
          - "5.5"
          - "8.4"
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: opcache
          coverage: none
          tools: none
      -
        name: Check syntax
        uses: mlocati/check-php-syntax@v1
        with:
          fail-on-warnings: true

  check-install:
    name: Install on Concrete ${{ matrix.ccm-version }}
    runs-on: ubuntu-latest
    container: ghcr.io/concrete5-community/docker5:${{ matrix.ccm-version }}
    strategy:
      matrix:
        ccm-version:
          - 8.5.2
          - "9.0"
          - "9.1"
          - "9.2"
          - latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
      -
        name: Check composer.json
        run: sudo -u www-data composer --ansi --no-interaction validate --strict -- "$GITHUB_WORKSPACE/composer.json"
      -
        name: Prepare package
        run: ln -s "$GITHUB_WORKSPACE" /app/packages/iubenda
      -
        name: Start services
        run: ccm-service start db
      -
        name: Core info
        run: sudo -u www-data /app/concrete/bin/concrete5 --ansi --no-interaction c5:info
      -
        name: Download dependencies
        working-directory: /app/packages
        run: |
          curl -sSLf -o temp.zip https://github.com/concrete5-community/http_client_compat/releases/download/1.0.0/http_client_compat-v1.0.0.zip
          sudo -u www-data unzip temp.zip
          rm temp.zip
      -
        name: Install dependencies
        run: sudo -u www-data /app/concrete/bin/concrete5 --ansi --no-interaction c5:package:install http_client_compat
      -
        name: Install package
        run: sudo -u www-data /app/concrete/bin/concrete5 --ansi --no-interaction c5:package:install iubenda
